---
- hosts: master-nodes
  tasks:
  - name: Copying Discovery service deployment file to cluster
    copy: src=/var/lib/jenkins/workspace/discovery-service-US/discovery-service.yml dest=/root/discovery-service.yml
  - name: Deploying Discovery service
    shell: |
     kubectl apply -f discovery-service.yml
     kubectl rollout restart deployment  discovery-service
  - name: Copying config service deployment file to cluster
    copy: src=/var/lib/jenkins/workspace/config-service-US/config-service.yml dest=/root/config-service.yml
  - name: Deploying Config Service
    shell: |
     kubectl apply -f config-service.yml
     kubectl rollout restart deployment  config-service
  - name: Copying Message service deployment file to cluster
    copy: src=/var/lib/jenkins/workspace/message-service-US/message-service.yml dest=/root/message-service.yml
  - name: Deploying Message Service   
    shell: |
     kubectl apply -f message-service.yml
     kubectl rollout restart deployment  message-service
  - name: Copying payment response service deployment file to cluster     
    copy: src=/var/lib/jenkins/workspace/payment-response-service-US/payment-response-service.yml dest=/root/payment-response-service.yml
  - name: Deploying payment response service
    shell: | 
     kubectl apply -f payment-response-service.yml
     kubectl rollout restart deployment  payment-response-service
  - name: Copying payment service deployment file to cluster
    copy: src=/var/lib/jenkins/workspace/payment-service-US/payment-service.yml dest=/root/payment-service.yml
  - name: Deploying payment service
    shell: | 
     kubectl apply -f payment-service.yml
     kubectl rollout restart deployment  payment-service
  - name: Copying rpp connector service deployment file to cluster
    copy: src=/var/lib/jenkins/workspace/rpp-connector-service-US/rpp-connector-service.yml dest=/root/rpp-connector-service.yml
  - name: Deploying rpp connector service
    shell: |
     kubectl apply -f rpp-connector-service.yml
     kubectl rollout restart deployment  rpp-connector-service
  - name: Copying traditional message service deployment file to cluster
    copy: src=/var/lib/jenkins/workspace/traditional-message-service-US/traditional-message-service.yml dest=/root/traditional-message-service.yml
  - name: Deploying Traditional message service
    shell: | 
     kubectl apply -f traditional-message-service.yml
     kubectl rollout restart deployment  traditional-message-service
  - name: Copying trasform service deployment file to cluster   
    copy: src=/var/lib/jenkins/workspace/transform-service-US/transform-service.yml dest=/root/transform-service.yml
  - name:  Deploying transform service
    shell: |
     kubectl apply -f transform-service.yml
     kubectl rollout restart deployment  transform-service
  - name: Copying Add-on file to cluster   
    copy: src=/var/lib/jenkins/workspace/database dest=/root/database
