---
- hosts: monitoring-node
  tasks:
  - name: Installing Docker
    block:
      - name: Installing Docker
        shell: |
         sudo yum install -y yum-utils
         sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
         sudo yum install -y docker-ce docker-ce-cli containerd.io
         #dnf install docker-ce -y
    rescue:
      - name: Reinstalling with dnf
        shell: |
         dnf -y upgrade
         #dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
         #dnf install https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.6-3.3.el7.x86_64.rpm
         #dnf install docker-ce -y --nobest
         sudo dnf install docker-ce-3:18.09.1-3.el7
         sudo systemctl enable --now docker
         sudo dnf install https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.6-3.3.el7.x86_64.rpm
         sudo dnf install docker-ce
    - name: Starting and Enabling docker
      service:
      name: docker
      state: started
      enabled: yes
         
    - 
      name: "Install Docker-Compose"
      shell: |
          curl -L "https://github.com/docker/compose/releases/download/1.25.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose         
    - 
      name: "Deploying elk in docker"
      shell: |
          cd /root/database/logging
          sysctl -w vm.max_map_count=262144
          cat > /etc/sysctl.conf << EOF
          vm.max_map_count=262144
          EOF
          iptables -t filter -N DOCKER
          systemctl restart docker
          docker-compose up -d  
    - 
      name: "Deploying Prometheus and Grafana"
      shell: |
          cd /root/database/monitoring
          sed -i "s|{promethus_url}|${masterNode}|g" grafana/provisioning/datasources/datasource.yml
          docker-compose up -d
- hosts: database-nodes
  tasks:          
  - name: "Choosen database"
    debug:
      msg: "The database is {{ kube_database }}"        
  - name: Install mongodb
    - name: Ensure mongo Repository is Installed
      yum_repository:
        name: MongoDB Repository
        state: present
        description: Official mongo Yum Repo
        baseurl: https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/4.4/x86_64/
        gpgkey: https://www.mongodb.org/static/pgp/server-4.4.asc
        gpgcheck: yes
        enabled: yes
    - name: install mongodb
      yum: name=mongodb-org state=latest update_cache=yes
      notify:
      - start mongodb
  handlers:
    - name: start mongodb
      service: name=mongod state=started
    when:
      - kube_database == "mongo"
  - name: Install postgresql      
    shell: |
      sudo yum install https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
      sudo yum -y install epel-release yum-utils
      sudo yum-config-manager --enable pgdg12
      sudo yum install postgresql12-server postgresql12 -y
      sudo /usr/pgsql-12/bin/postgresql-12-setup initdb
      sudo systemctl start postgresql-12
      sudo systemctl enable postgresql-12
      echo "Ecssupport09" | sudo passwd postgres --stdin
      sudo su - postgres 
      psql -c "alter user postgres with password 'Ecssupport09'"
      /q
    when:
      - kube_database == "postgres"
  - name: Install mongodb docker       
    shell: |
      docker run -d --name mongo0 -p 27018:27017 -v data:/data/db mongo
    when:
      - kube_database == "mongo_docker"
