logging_ns: logging
monitoring_ns: monitoring
messaging_ns: kafka
operations_ns: operations
deployment_ns: rpp-dev
redis_ns: redis
zeebe_ns: zeebe
load_balancer_ns: load-balancer
Rancher_dashboard: disabled
Cluster_Logging: disabled
Cluster_Monitoring: disabled
Auto_scaling: disabled
Zeebe: disabled
Mongo: disabled
Redis: enabled
Kafka: enabled
slack_token: xoxb-666314487104-1537231431378-4ICWQKmZa7KOEPUEkSJqZN3F
slack_channel: "#cluster_monitoring"
Loadbalancer_ip_range: 192.168.45.121-192.168.45.140
elk_replicas: 1
kube_network_plugin: calico
kong_loadBalancerIP: 192.168.45.125
nexus_ip: 192.168.45.27:8082
kube_database: mongo
spring_profiles: 'dev,rfi_dev'