logging_ns: logging
monitoring_ns: monitoring
messaging_ns: kafka
operations_ns: operations
deployment_ns: deployment
zeebe_ns: workflow
Rancher_dashboard: disabled
Cluster_Logging: disabled
Cluster_Monitoring: disabled
Auto_scaling: disabled
load_balancer_ns: load-balancer
slack_token: xoxb-1075050838129-1068657729780-eqo8RLuSRy8jdwMq8GNtyRBW
slack_channel: "#random"
Loadbalancer_ip_range: 192.168.45.200-192.168.45.220
elk_replicas: 1
kube_network_plugin: flannel
kong_loadBalancerIP: 192.168.45.202
nexus_ip: 192.168.45.27:8082
kube_database: mongo