---
- hosts: all
  become: yes
  tasks:
  - name: Include vars
    include_vars: "config_var.yaml"  
  - name: Install a list of packages
    yum:
      name:
        - dnf
        - dnf-plugins-core
      state: present
  - name: Add IP address of all hosts to all hosts
    lineinfile:
      dest: /etc/hosts
      regexp: '.*{{ item }}$'
      line: "{{ hostvars[item].ansible_host }} {{item}}"
      state: present
    when: hostvars[item].ansible_host is defined
    with_items: "{{ groups.all }}"
  - name: Disabling Swap on all nodes
    shell: |
     sudo swapoff -a
  - name: Disable SWAP in fstab since kubernetes can't work with swap enabled (2/2)
    replace:
      path: /etc/fstab
      regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
      replace: '# \1'      
  - name: Set Hostname
    shell: hostnamectl set-hostname {{ inventory_hostname }}
  - name: Disable firewalld
    shell: |
     sudo systemctl disable firewalld
     sudo systemctl stop firewalld
  - name: Enabling Bridge Firewall Rule
    shell: |
     modprobe br_netfilter
     echo '1' > /proc/sys/net/bridge/bridge-nf-call-iptables
  - name: Installing Docker
    block:
      - name: Installing Docker
        shell: |
         sudo yum install -y -q yum-utils device-mapper-persistent-data lvm2 > /dev/null 2>&1
         sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo > /dev/null 2>&1
         sudo yum install -y docker-ce docker-ce-cli containerd.io
         #sudo yum install -y docker-ce-19.03.12 
    rescue:
      - name: Reinstalling with dnf
        shell: |
         dnf -y upgrade
         #dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
         #dnf install https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.6-3.3.el7.x86_64.rpm
         #dnf install docker-ce -y --nobest
         sudo dnf install docker-ce-3:18.09.1-3.el7
         sudo systemctl enable --now docker
         sudo dnf install https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.6-3.3.el7.x86_64.rpm
         sudo dnf install docker-ce
  - name: Creating a repository file for Kubernetes
    file:
     path: /etc/yum.repos.d/kubernetes.repo
     state: touch
  - name: Adding repository details in Kubernetes repo file.
    blockinfile:
     path: /etc/yum.repos.d/kubernetes.repo
     block: |
      [kubernetes]
      name=Kubernetes
      baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
      enabled=1
      gpgcheck=1
      repo_gpgcheck=1
      gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
  - name: Installing kubeadm
    shell: |
     sudo yum install -y kubelet kubeadm kubectl --disableexcludes=kubernetes
     #yum install -y kubeadm-1.18.5-0 kubelet-1.18.5-0 kubectl-1.18.5-0
  - name: Starting and Enabling docker
    service:
     name: docker
     state: started
     enabled: yes
  - name: Starting and Enabling kubelet
    shell: |
     sudo systemctl enable --now kubelet
     sudo systemctl start kubelet
  - name: Enable the usage of iptables
    shell: |
     sudo bash -c 'echo "net.bridge.bridge-nf-call-ip6tables = 1" > /etc/sysctl.d/k8s.conf'
     sudo bash -c 'echo "net.bridge.bridge-nf-call-iptables = 1" >> /etc/sysctl.d/k8s.conf'
     cat >>/etc/sysctl.d/kubernetes.conf<<EOF
     net.bridge.bridge-nf-call-ip6tables = 1
     net.bridge.bridge-nf-call-iptables = 1
     EOF
     sudo sysctl --system
- hosts: all
  tasks:
  - name: Create docker daemon file
    copy: src=daemon.json dest=/etc/docker/daemon.json
  - name: Reloading docker daemon
    shell: |
     sudo systemctl daemon-reload
     sudo systemctl restart docker
  - name: Logging into docker nexus repository
    shell: docker login -u admin -p Ecssupport09 {{ nexus_ip }}
- hosts: master-nodes
  tasks:
  - name: "Master ip address"
    debug:
      msg: "{{ ansible_eth0.ipv4.address }}"
  
  - name: Initializing Kubernetes cluster
    shell: |
     sudo kubeadm config images pull
     sudo kubeadm init 
    when:
      - kube_network_plugin == "weave"
    shell: |
     sudo kubeadm config images pull
     kubeadm init --apiserver-advertise-address={{ ansible_eth0.ipv4.address }} --pod-network-cidr 10.244.0.0/16
    when: 
      - kube_network_plugin != "weave"
    register: output
  - name: Storing Logs and Generated token for future purpose.
    local_action: copy content={{ output.stdout }} dest=/bin/join_token
  - name: Copying required files
    shell: |
     mkdir -p $HOME/.kube
     sudo cp -f /etc/kubernetes/admin.conf $HOME/.kube/config
     sudo chown $(id -u):$(id -g) $HOME/.kube/config
  - name: "Cluster n/w "
    debug:
      msg: "The cluster network is {{ kube_network_plugin }}"        
  - name: Install Network Add-on weave 
    shell: |
     export kubever=$(kubectl version | base64 | tr -d '\n')
     kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$kubever"
    when:
      - kube_network_plugin == "weave"
  - name: Install Network Add-on calico   
    shell: |
      #kubectl apply -f /root/kube_additional/operations/calico.yaml
      kubectl --kubeconfig=/etc/kubernetes/admin.conf create -f https://docs.projectcalico.org/v3.14/manifests/calico.yaml
    when:
      - kube_network_plugin == "calico"
  - name: Install Network Add-on flannel  
    shell: |
      sudo kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
    when:
      - kube_network_plugin == "flannel"      
- hosts: worker-nodes
  tasks:
  - name: Copying token to worker nodes
    copy: src=/bin/join_token dest=/bin/join_token
  - name: Joining worker nodes with kubernetes master
    shell: |
     cat /bin/join_token | tail -2 > out.sh
     sh out.sh
- hosts: master-nodes
  tasks:
  - name:  installing helm
    shell: |
     curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
     chmod 700 get_helm.sh
     ./get_helm.sh
    ignore_errors: yes
- hosts: all
  tasks:
    - name: install nfs utils
      yum:
        name: nfs-utils
        state: present
    - name: check date
      command: date
      register: out
    - debug: msg={{out.stdout}}
    - pause: seconds=30
- hosts: master-nodes
  tasks:    
    - name:  installing metrics-server
      shell: |
       helm repo add stableOld https://kubernetes-charts.storage.googleapis.com
       helm repo add stable https://charts.helm.sh/stable
       helm repo update
       kubectl create ns {{ operations_ns }}
       helm install metrics-server stable/metrics-server --namespace {{ operations_ns }} --values /root/kube_additional/operations/metrics-server.values
      ignore_errors: yes
    - name:  creating spring profiles configMap
      shell: |
       kubectl create ns  {{ deployment_ns }}
       kubectl label nodes master-node dedicated=master
       kubectl create configmap profile-config --from-literal profile="{{ spring_profiles }}" -n {{ deployment_ns }}
    