---
- hosts: master-nodes
  tasks:
  - name: detaching all node
    shell: kubectl delete node --all
    ignore_errors: yes
- hosts: all
  become: yes
  tasks:
  - name: Removing docker daemon file
    shell: rm -rf /etc/docker/daemon.json
  - name: Reset kubernetes
    shell: kubeadm reset -f 
    ignore_errors: yes
  - name: Stop Disable kubernetes
    shell: |
     systemctl disable kubelet
     systemctl stop kubelet
    ignore_errors: yes
  - name: Remove kubernetes
    shell: yum remove kubeadm kubectl kubelet kubernetes-cni kube* -y 
    ignore_errors: yes
  - name: Remove related s/w & files
    shell: |
     yum autoremove -y
     rm -rf ~/.kube
     rm -rf /etc/cni /etc/kubernetes /var/lib/dockershim /var/lib/etcd /var/lib/kubelet /var/run/kubernetes ~/.kube/*
    ignore_errors: yes
  - name: Resetting iptables in master-nodes
    shell: |
     rm -rf /etc/cni/net.d
     iptables -F && iptables -t nat -F && iptables -X
     iptables -t nat -X && iptables -t raw -F && iptables -t raw -X
     iptables -t mangle -F && iptables -t mangle -X
     #ipvsadm -C
    ignore_errors: yes
  - name: Removing docker from all nodes
    shell: |
     docker system prune -f
     docker network prune -f
     docker stop $(docker ps -a -q)
     docker rm $(docker ps -a -q) -f
     docker rmi $(docker images -a -q) -f
     yum remove docker docker-client docker-client-latest docker-common docker-latest docker-latest-logrotate docker-logrotate docker-engine -y
     sudo yum remove docker-ce docker-ce-cli containerd.io -y
     sudo rm -rf /var/lib/docker
  - name: Delete ssh keys
    shell: rm -rf /root/.ssh/authorized_keys
